branches:
  except:
    - gh-pages
language: perl
env:
  - PERL_USE_UNSAFE_INC=0
perl:
  - "5.38.2"
  - "5.36.3"
  - "5.34.3"
  - "5.32.1"
  - "5.30.3"
  - "5.28.3"
  - "5.26.3"
  - "5.24.4"
  - "5.22.4"
  - "5.20.3"
  - "5.18.4" # IO::Tty is missing on the Travis server or cannot be installed?
  - "5.16.3"
  - "5.14.4"
  - "5.12.5"
  - "5.10.1"
